In [1]:
import pandas as pd
import numpy as np

In [8]:
# Carregando o dataset
use_cols = ['Territorialidades','IDHM 2012','IDHM 2013','IDHM 2014','IDHM 2015','IDHM 2016','IDHM 2017','IDHM 2018','IDHM 2019','IDHM 2020','IDHM 2021',
            'IDHM Renda 2012', 'IDHM Renda 2013', 'IDHM Renda 2014', 'IDHM Renda 2015', 'IDHM Renda 2016', 'IDHM Renda 2017', 
            'IDHM Renda 2018', 'IDHM Renda 2019', 'IDHM Renda 2020', 'IDHM Renda 2021']
df = pd.read_csv('../data/idh.csv', usecols=use_cols)

In [20]:
df.head()

,Territorialidades,IDHM Renda 2012,IDHM Renda 2013,IDHM Renda 2014,IDHM Renda 2015,IDHM Renda 2016,IDHM Renda 2017,IDHM Renda 2018,IDHM Renda 2019,IDHM Renda 2020,...,IDHM 2012,IDHM 2013,IDHM 2014,IDHM 2015,IDHM 2016,IDHM 2017,IDHM 2018,IDHM 2019,IDHM 2020,IDHM 2021
0,BR,0.732,0.737,0.741,0.736,0.734,0.735,0.741,0.743,0.736,...,0.746,0.753,0.762,0.765,0.771,0.774,0.780,0.785,0.784,0.766
1,AC,0.670,0.670,0.669,0.674,0.660,0.655,0.676,0.668,0.668,...,0.701,0.706,0.715,0.718,0.723,0.712,0.733,0.739,0.746,0.710
2,AL,0.627,0.629,0.645,0.636,0.637,0.631,0.637,0.636,0.645,...,0.651,0.648,0.666,0.666,0.680,0.679,0.689,0.687,0.694,0.684
3,AP,0.673,0.691,0.687,0.690,0.682,0.683,0.666,0.665,0.663,...,0.707,0.734,0.725,0.728,0.733,0.732,0.741,0.737,0.724,0.688
4,AM,0.683,0.683,0.683,0.673,0.654,0.672,0.655,0.658,0.657,...,0.691,0.702,0.706,0.711,0.711,0.728,0.718,0.726,0.727,0.700

In [10]:
# explore data analysis
print(df.shape)
print(df.info())
print(df.describe())
print(df.head())

(28, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Territorialidades  28 non-null     object
 1   IDHM Renda 2012    27 non-null     float64
 2   IDHM Renda 2013    27 non-null     float64
 3   IDHM Renda 2014    27 non-null     float64
 4   IDHM Renda 2015    27 non-null     float64
 5   IDHM Renda 2016    27 non-null     float64
 6   IDHM Renda 2017    27 non-null     float64
 7   IDHM Renda 2018    27 non-null     float64
 8   IDHM Renda 2019    27 non-null     float64
 9   IDHM Renda 2020    27 non-null     float64
 10  IDHM Renda 2021    27 non-null     float64
 11  IDHM 2012          27 non-null     float64
 12  IDHM 2013          27 non-null     float64
 13  IDHM 2014          27 non-null     float64
 14  IDHM 2015          27 non-null     float64
 15  IDHM 2016          27 non-null     float64
 16  IDHM 2017          27 non-null     float64
 17  IDHM 2018          27 non-null     float64
 18  IDHM 2019          27 non-null     float64
 19  IDHM 2020          27 non-null     float64
 20  IDHM 2021          27 non-null     float64
dtypes: float64(20), object(1)
memory usage: 4.7+ KB
None
       IDHM Renda 2012  IDHM Renda 2013  IDHM Renda 2014  IDHM Renda 2015  \
count        27.000000        27.000000        27.000000        27.000000
mean          0.702333         0.708815         0.712593         0.709370
std           0.055963         0.054500         0.053089         0.051639
min           0.602000         0.607000         0.610000         0.613000
25%           0.662000         0.668500         0.673500         0.673500
50%           0.683000         0.691000         0.698000         0.690000
75%           0.732000         0.739000         0.742000         0.736000
max           0.846000         0.848000         0.845000         0.847000

       IDHM Renda 2016  IDHM Renda 2017  IDHM Renda 2018  IDHM Renda 2019  \
count        27.000000        27.000000        27.000000        27.000000
mean          0.704481         0.706037         0.710296         0.710963
std           0.053159         0.053653         0.054724         0.055955
min           0.615000         0.616000         0.613000         0.614000
25%           0.661000         0.670500         0.666500         0.670000
50%           0.687000         0.687000         0.698000         0.693000
75%           0.737500         0.736500         0.747000         0.749500
max           0.836000         0.842000         0.836000         0.841000

       IDHM Renda 2020  IDHM Renda 2021  IDHM 2012  IDHM 2013  IDHM 2014  \
count        27.000000        27.000000  27.000000  27.000000  27.000000
mean          0.707000         0.694074   0.721852   0.730259   0.738407
std           0.050164         0.053610   0.048310   0.049379   0.046964
min           0.621000         0.603000   0.648000   0.648000   0.663000
25%           0.665500         0.648500   0.686000   0.692500   0.701000
50%           0.691000         0.684000   0.710000   0.734000   0.737000
75%           0.740000         0.728500   0.754000   0.761500   0.771000
max           0.827000         0.821000   0.825000   0.837000   0.836000

       IDHM 2015  IDHM 2016  IDHM 2017  IDHM 2018  IDHM 2019  IDHM 2020  \
count  27.000000  27.000000  27.000000  27.000000  27.000000  27.000000
mean    0.741704   0.746556   0.748963   0.755741   0.759370   0.754111
std     0.045835   0.047136   0.045357   0.045064   0.046967   0.036579
min     0.666000   0.680000   0.679000   0.686000   0.687000   0.694000
25%     0.707000   0.708000   0.714500   0.714500   0.722000   0.724000
50%     0.733000   0.734000   0.740000   0.749000   0.749000   0.755000
75%     0.775000   0.777500   0.782000   0.786000   0.793000   0.784500
max     0.837000   0.847000   0.842000   0.845000   0.859000   0.829000

       IDHM 2021
count  27.000000
mean    0.732593
std     0.039995
min     0.676000
25%     0.698500
50%     0.731000
75%     0.767500
max     0.814000
  Territorialidades  IDHM Renda 2012  IDHM Renda 2013  IDHM Renda 2014  \
0                BR            0.732            0.737            0.741
1                AC            0.670            0.670            0.669
2                AL            0.627            0.629            0.645
3                AP            0.673            0.691            0.687
4                AM            0.683            0.683            0.683

   IDHM Renda 2015  IDHM Renda 2016  IDHM Renda 2017  IDHM Renda 2018  \
0            0.736            0.734            0.735            0.741
1            0.674            0.660            0.655            0.676
2            0.636            0.637            0.631            0.637
3            0.690            0.682            0.683            0.666
4            0.673            0.654            0.672            0.655

   IDHM Renda 2019  IDHM Renda 2020  ...  IDHM 2012  IDHM 2013  IDHM 2014  \
0            0.743            0.736  ...      0.746      0.753      0.762
1            0.668            0.668  ...      0.701      0.706      0.715
2            0.636            0.645  ...      0.651      0.648      0.666
3            0.665            0.663  ...      0.707      0.734      0.725
4            0.658            0.657  ...      0.691      0.702      0.706

   IDHM 2015  IDHM 2016  IDHM 2017  IDHM 2018  IDHM 2019  IDHM 2020  IDHM 2021
0      0.765      0.771      0.774      0.780      0.785      0.784      0.766
1      0.718      0.723      0.712      0.733      0.739      0.746      0.710
2      0.666      0.680      0.679      0.689      0.687      0.694      0.684
3      0.728      0.733      0.732      0.741      0.737      0.724      0.688
4      0.711      0.711      0.728      0.718      0.726      0.727      0.700

[5 rows x 21 columns]

In [14]:
# valores faltantes
print(df.isnull().sum())

Territorialidades    0
IDHM Renda 2012      0
IDHM Renda 2013      0
IDHM Renda 2014      0
IDHM Renda 2015      0
IDHM Renda 2016      0
IDHM Renda 2017      0
IDHM Renda 2018      0
IDHM Renda 2019      0
IDHM Renda 2020      0
IDHM Renda 2021      0
IDHM 2012            0
IDHM 2013            0
IDHM 2014            0
IDHM 2015            0
IDHM 2016            0
IDHM 2017            0
IDHM 2018            0
IDHM 2019            0
IDHM 2020            0
IDHM 2021            0
dtype: int64

In [16]:
# verificando valores duplicados
print(df.duplicated().sum())

0

In [17]:
# verificando valores Ãºnicos
print(df.nunique())

Territorialidades    27
IDHM Renda 2012      23
IDHM Renda 2013      25
IDHM Renda 2014      23
IDHM Renda 2015      24
IDHM Renda 2016      26
IDHM Renda 2017      25
IDHM Renda 2018      24
IDHM Renda 2019      25
IDHM Renda 2020      26
IDHM Renda 2021      25
IDHM 2012            26
IDHM 2013            26
IDHM 2014            25
IDHM 2015            26
IDHM 2016            25
IDHM 2017            25
IDHM 2018            24
IDHM 2019            26
IDHM 2020            24
IDHM 2021            25
dtype: int64

In [31]:
df_temp = pd.read_csv('../data/prepareted-data/average_temp_brazil.csv')
df_temp.head()

   UF  media   ano
0  RS  21.39  2000
1  RJ  23.14  2000
2  AM  27.29  2000
3  BA  26.32  2000
4  DF  21.57  2000